name: Be With You
description: 在没有人看得到你的时候
author: Wenjie Luo
url: http://wenjie-luo.com
timezone: America/Chicago

markdown: redcarpet
pygments: true
# permalink: /:year/:month/:day/:title.html
# logo: /assets/images/profile.png
paginate: 4

disqus: "wenjieblog"


navigations:
  - title: Home
    class: fa fa-home
    href: /
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Gallery
    class: fa fa-film
    href: http://photos.wenjie-luo.com
  - title: About
    class: fa fa-user
    href: /about.html	